In [2]:
import numpy as np

## 7

1)а) Решить методом Крамера:

In [15]:
A = np.array([[1,-2],[3,-4]])
A1 = np.array([[1,-2],[7,-4]])
A2 = np.array([[1,1],[3,7]])

In [16]:
x1 = np.linalg.det(A1)/np.linalg.det(A)
x1

4.999999999999998

In [17]:
x2 = np.linalg.det(A2)/np.linalg.det(A)
x2

1.9999999999999996

б)

In [18]:
A = np.array([[2,-1,5],[1,1,-3],[2,4,1]])
A1 = np.array([[10,-1,5],[-2,1,-3],[1,4,1]])
A2 = np.array([[2,10,5],[1,-2,-3],[2,1,1]])
A3 = np.array([[2,-1,10],[1,1,-2],[2,4,1]])

In [19]:
x1 = np.linalg.det(A1)/np.linalg.det(A)
x1

2.0000000000000018

In [20]:
x2 = np.linalg.det(A2)/np.linalg.det(A)
x2

-1.0000000000000009

In [21]:
x3 = np.linalg.det(A3)/np.linalg.det(A)
x3

1.0

2)а)

In [41]:
A = np.array([[1,2,4],[2,9,12],[3,26,30]])
A

10.000000000000016

In [42]:
A[1] = A[1] - (A[0]*2)

In [43]:
A[2] = A[2] - (A[0]*3)
A

array([[ 1,  2,  4],
       [ 0,  5,  4],
       [ 0, 20, 18]])

In [44]:
A[2] = A[2] - A[1]*4
A

array([[1, 2, 4],
       [0, 5, 4],
       [0, 0, 2]])

In [49]:
L = np.array([[1,0,0],[2,1,0],[3,4,1]]) #ответ
L

array([[1, 0, 0],
       [2, 1, 0],
       [3, 4, 1]])

In [50]:
np.dot(L,A) # проверка

array([[ 1,  2,  4],
       [ 2,  9, 12],
       [ 3, 26, 30]])

2)б)

In [51]:
A = np.array([[1,1,2,4],[2,5,8,9],[3,18,29,18],[4,22,53,33]])
A

array([[ 1,  1,  2,  4],
       [ 2,  5,  8,  9],
       [ 3, 18, 29, 18],
       [ 4, 22, 53, 33]])

In [52]:
A[1] = A[1]-A[0]*2
A[2] = A[2]-A[0]*3
A[3] = A[3]-A[0]*4
A

array([[ 1,  1,  2,  4],
       [ 0,  3,  4,  1],
       [ 0, 15, 23,  6],
       [ 0, 18, 45, 17]])

In [53]:
A[2]=A[2]-A[1]*5
A[3]=A[3]-A[1]*6
A

array([[ 1,  1,  2,  4],
       [ 0,  3,  4,  1],
       [ 0,  0,  3,  1],
       [ 0,  0, 21, 11]])

In [54]:
A[3]=A[3]-A[2]*7
A

array([[1, 1, 2, 4],
       [0, 3, 4, 1],
       [0, 0, 3, 1],
       [0, 0, 0, 4]])

In [55]:
L = np.array([[1,0,0,0],[2,1,0,0],[3,5,1,0],[4,6,7,1]]) #ответ
L

array([[1, 0, 0, 0],
       [2, 1, 0, 0],
       [3, 5, 1, 0],
       [4, 6, 7, 1]])

In [56]:
np.dot(L,A) #проверка

array([[ 1,  1,  2,  4],
       [ 2,  5,  8,  9],
       [ 3, 18, 29, 18],
       [ 4, 22, 53, 33]])

3)

In [61]:
A = np.array([[2,1,3],[11,7,5],[9,8,4]],dtype='f')
A

array([[ 2.,  1.,  3.],
       [11.,  7.,  5.],
       [ 9.,  8.,  4.]], dtype=float32)

In [62]:
A[1]=A[1]-A[0]*5.5
A[2]=A[2]-A[0]*4.5
A

array([[  2. ,   1. ,   3. ],
       [  0. ,   1.5, -11.5],
       [  0. ,   3.5,  -9.5]], dtype=float32)

In [63]:
A[2] = A[2] - A[1]*(7/3)
A

array([[  2.      ,   1.      ,   3.      ],
       [  0.      ,   1.5     , -11.5     ],
       [  0.      ,   0.      ,  17.333332]], dtype=float32)

In [65]:
L = np.array([[1,0,0],[5.5,1,0],[4.5,7/3,1]],dtype='f')
L

array([[1.       , 0.       , 0.       ],
       [5.5      , 1.       , 0.       ],
       [4.5      , 2.3333333, 1.       ]], dtype=float32)

In [67]:
y1 = 1

In [70]:
y2 = -6-(5.5*y1)
y2

-11.5

In [71]:
y3 = -5 - 4.5*y1 -7/3*y2
y3

17.333333333333336

In [73]:
x3 = 1
x2 = (-11.5+11.5*x3)/1.5
x2

0.0

In [75]:
x1 = (1-x2 -3*x3)/2
x1

-1.0

4)