# 1 часть

1. Исследовать на линейную зависимость:
f1(x)=ex,f2(x)=1,f3(x)=x+1,f4(x)=x−ex.

Решение: Заметим, что  f4(x)=f3(x)-f1(x)-f2(x) , то есть вектор  f4(x)  — линейная комбинация векторов  f1(x),f2(x)  и  f3(x) , из чего можно сделать вывод, что  f1(x),f2(x),f3(x)  и  f4(x)  линейно зависимы.

2. Исследовать на линейную зависимость:
f1(x)=2,f2(x)=x,f3(x)=x^2,f4(x)=(x+1)^2.

Решение: f4(x) = x^2 +2x +1, то есть f4(x) = f3(x) + 2*f2(x) + 0.5*f1(x). Значит, f1(x),f2(x),f3(x) и f4(x) линейно зависимы.

3. Найти координаты вектора  x=(2,3,5)∈R3  в базисе  b1=(0,0,10) ,  b2=(2,0,0) ,  b3=(0,1,0) .

Решение: x = 0.5b1+b2+3b3, 
то есть координатами вектора x в стандартном базисе являются 0.5, 1, 3.

4. Найти координаты вектора  3x2−2x+2∈R3[x] :

а) в базисе  1 ,  x ,  x2 ;

б) в базисе  x2 ,  x−1 ,  1 .

Решение: a) вектор (2, -2x, 3x^2) будет иметь координаты (2, -2, 3) (2*e1, -2e2, 3e3)

Решение: б) вектор (3x^2, -2x, 2) можно выразить как 3e1, -2e2, 0e3, координаты (3, -2, 0)

5. Установить, является ли линейным подпространством:

а) совокупность всех векторов трехмерного пространства, у которых по крайней мере одна из первых двух координат равна нулю;

б) все векторы, являющиеся линейными комбинациями данных векторов  {u1,u2,...,un} .

Решение: а) например, вектор (0,a,b) и (c,0,d). Если их сложить, имеем(c,a,b+d). Условие не выполняется, т.к. ни одна из первых двух координат не = 0

Решение: б) например вектор a = n1*u1 +n2*u2...nn*un
вектор b = i1*u1 +i2*u2...in*un

если их сложить, имеем вектор d= (i1+n1)u1 + (i2+n2)u2+...+(in+nn)un
если умножить на скаляр c = k*n1*u1+k*n2*u2...k*nn*un
Условия выполняются, значит линейным подпространством эта совокупность является.

# 2 часть

1. Найти скалярное произведение векторов  x,y∈R :
а)  x=(0,−3,6), y=(−4,7,9); 
б)  x=(7,−4,0,1), y=(−3,1,11,2). 
2. Найти нормы векторов  (4,2,4)  и  (12,3,4)  и угол между ними.

3. Будет ли линейное пространство евклидовым, если за скалярное произведение принять:
а) произведение длин векторов;
б) утроенное обычное скалярное произведение векторов?

4. Какие из нижеперечисленных векторов образуют ортонормированный базис в линейном пространстве  R3 :
а)  (1,0,0),(0,0,1); 
б)  (1/2–√,−1/2–√,0),(1/2–√,1/2–√,0),(0,0,1); 
в)  (1/2,−1/2,0),(0,1/2,1/2),(0,0,1); 
г)  (1,0,0),(0,1,0),(0,0,1)?

1.а)

In [8]:
import numpy as np
from numpy.linalg import norm

In [4]:
a = np.array([0, -3, 6])
b = np.array([-4, 7, 9])
print(f'Скалярное произведение a и b:{np.dot(a, b)}')

Скалярное произведение a и b:33


1.б)

In [5]:
a = np.array([7, -4, 0, 1])
b = np.array([-3, 1, 11, 2])
print(f'Скалярное произведение a и b:{np.dot(a, b)}')

Скалярное произведение a и b:-23


2)

In [6]:
a = np.array([4,2,4])
b = np.array([12,3,4])

In [13]:
print (f'Норма вектора а: {norm(a):.2f}, Норма вектора b: {norm(b):.2f} ')

Норма вектора а: 6.00, Норма вектора b: 13.00 


In [11]:
cos_phi = np.dot(a, b) / norm(a) / norm(b)
print(f'Косинус угла между a и b: {cos_phi:.2f}')
print(f'Угол между a и b: {np.arccos(cos_phi):.2f}')

Косинус угла между a и b: 0.90
Угол между a и b: 0.46


4)

ортонормированный базис образуют только векторы из пункта г)(1,0,0),(0,1,0),(0,0,1)

# 3 часть

Все задания рекомендуется делать вручную, затем проверяя полученные результаты с использованием numpy.

1. Установить, какие произведения матриц  AB  и  BA  определены, и найти размерности полученных матриц:

а)  A  — матрица  4×2 ,  B  — матрица  4×2 ;

б)  A  — матрица  2×5 ,  B  — матрица  5×3 ;

в)  A  — матрица  8×3 ,  B  — матрица  3×8 ;

г)  A  — квадратная матрица  4×4 ,  B  — квадратная матрица  4×4 .

2. Найти сумму и произведение матриц  A=(13−20)  и  B=(40−15). 
3. Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию  3A−2B+4C  для матриц  A=(137−6) ,  B=(025−1) ,  C=(21−41). 
4. Дана матрица  A=⎛⎝⎜4521−23⎞⎠⎟ . Вычислить  AAT  и  ATA .

5*. Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

1)

a) произведение не определено б) AB определено, размерность 2х3 в) AB и BA определены, размерность AB 8х8, BA 3х3 г) AB BA определены, размерности 4х4

2)

In [14]:
a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])
a+b

array([[ 5, -3],
       [ 3,  5]])

In [16]:
np.dot(a, b)

array([[  4, -11],
       [ 12,  -3]])

In [17]:
np.dot(b, a)

array([[ 1, -8],
       [15,  0]])

3)

In [18]:
a = np.array([[1, 7], [3, -6]])
b = np.array([[0, 5], [2, -1]])
c = np.array([[2, -4], [1, 1]])

In [19]:
3*a - 2*b + 4*c

array([[ 11,  -5],
       [  9, -12]])

4)

In [20]:
a = np.array([[4, 1], [5, -2], [2, 3]])

In [22]:
at = a.T
at

array([[ 4,  5,  2],
       [ 1, -2,  3]])

In [23]:
np.dot(a, at)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [24]:
np.dot(at, a)

array([[45,  0],
       [ 0, 14]])

5)

# 4 часть

1)

a) Получим sin^2(x) + cos^2(x) = 1

In [45]:
import math
a = np.array([[math.sin(1), -math.cos(1)],[math.cos(1), math.sin(1)]])
np.linalg.det(a)

1.0

б)

In [57]:
a = np.array([[4,2,3],[0,5,1],[0,0,9]])
det = 4*5*9
det

180

In [54]:
np.linalg.det(a)

180.0

в)

In [56]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
det = 1*(5*9-8*6)-2*(4*9-7*6)+3*(4*8-7*5)
det

0

In [51]:
np.linalg.det(a)

-9.51619735392994e-16

2)Определитель матрицы  A  равен  4 .

а)  det(A^2) = det(A)*det(A) = 16

б)  det(AT)=det(A) = 4

в)  det(2A) = 2*2*2det(A) = 32

3)

In [41]:
a = np.array([[-2,7,-3],[4,-14,6],[-3,7,13]])
a

array([[ -2,   7,  -3],
       [  4, -14,   6],
       [ -3,   7,  13]])

Вторая строка равна первой умноженной на (-2), значит строки линейно зависимы. Если две строки (столбца) матрицы линейно зависимы, то определитель этой матрицы равен нулю.

4)

In [42]:
a = np.array([[1,2,3],[1,1,1],[2,3,4]])
numpy.linalg.matrix_rank(a)

2

In [44]:
a = np.array([[0,0,2,1],[0,0,2,2],[0,0,4,3],[2,3,5,6]])
numpy.linalg.matrix_rank(a)

3