In [2]:
import numpy as np

# 6

1) Решить методом Гаусса

In [78]:
A = np.array([[1,1,-1,-2,0],[2,1,-1,1,-2],[1,1,-3,1,4]])
A

array([[ 1,  1, -1, -2,  0],
       [ 2,  1, -1,  1, -2],
       [ 1,  1, -3,  1,  4]])

In [79]:
A[1]=A[1]-A[0]*2
A[2]=A[2]-A[0]
A

array([[ 1,  1, -1, -2,  0],
       [ 0, -1,  1,  5, -2],
       [ 0,  0, -2,  3,  4]])

x3 =1.5x4 - 2

x2 = 2 + x3 + 5x4 = 2 + 1.5x4 - 2 + 5x4 = 6.5x4

x1 = x3 + 2x4 - x2 = 1.5x4 - 2 - 6.5x4 + 2x4 = 7x4 - 2

система имеет бесконечное число решений

2)Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

а)

In [80]:
a1 = (3,2,1)
a2 = (-1,5,1)
a3 = (1,-3,-1)
b = (4,-17,0)

b = a1 + 2a2 +3a3, значит, система совместна и имеет единственное решение

б)

In [81]:
a1 = (2,1,3)
a2 = (-4,-2,-6)
a3 = (6,3,9)
b = (1,-2,5)

векторы а1,а2,а3 линейно зависимы, а вектор b не принадлежит к этому подпространству, значит, система решений не имеет

в)

In [82]:
a1 = (1,3)
a2 = (2,1)
a3 = (5,-8)
b = (4,-2)

векторы лниейно независимы, система имеет бесконечное число решений

3)

In [83]:
A = np.array([[1,3,2,4],[0,5,0,1],[0,0,3,0],[0,0,0,2]])
Aw = np.array([[1,3,2,4,3],[0,5,0,1,2],[0,0,3,0,4],[0,0,0,2,1]])

In [86]:
rankA = np.linalg.matrix_rank(A)
rankAw = np.linalg.matrix_rank(Aw)
n = 4

In [87]:
print(rankA,rankAw,n)

4 4 4


система имеет единственное решение

4)

In [88]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
Aw = np.array([[1,2,3,a],[4,5,6,b],[7,8,9,c]])

NameError: name 'c' is not defined

Ранг матрицы коэффициентов = 2, значит, нужно, чтобы ранг расширенной матрицы был равен 3. Для этого после приведения матрицы к треугольному виду получаем неравенство

c - 7a - 2b + 8a =! 0

2b != c + a

## 7

1)а) Решить методом Крамера:

In [15]:
A = np.array([[1,-2],[3,-4]])
A1 = np.array([[1,-2],[7,-4]])
A2 = np.array([[1,1],[3,7]])

In [16]:
x1 = np.linalg.det(A1)/np.linalg.det(A)
x1

4.999999999999998

In [17]:
x2 = np.linalg.det(A2)/np.linalg.det(A)
x2

1.9999999999999996

б)

In [18]:
A = np.array([[2,-1,5],[1,1,-3],[2,4,1]])
A1 = np.array([[10,-1,5],[-2,1,-3],[1,4,1]])
A2 = np.array([[2,10,5],[1,-2,-3],[2,1,1]])
A3 = np.array([[2,-1,10],[1,1,-2],[2,4,1]])

In [19]:
x1 = np.linalg.det(A1)/np.linalg.det(A)
x1

2.0000000000000018

In [20]:
x2 = np.linalg.det(A2)/np.linalg.det(A)
x2

-1.0000000000000009

In [21]:
x3 = np.linalg.det(A3)/np.linalg.det(A)
x3

1.0

2)а)

In [41]:
A = np.array([[1,2,4],[2,9,12],[3,26,30]])
A

10.000000000000016

In [42]:
A[1] = A[1] - (A[0]*2)

In [43]:
A[2] = A[2] - (A[0]*3)
A

array([[ 1,  2,  4],
       [ 0,  5,  4],
       [ 0, 20, 18]])

In [44]:
A[2] = A[2] - A[1]*4
A

array([[1, 2, 4],
       [0, 5, 4],
       [0, 0, 2]])

In [49]:
L = np.array([[1,0,0],[2,1,0],[3,4,1]]) #ответ
L

array([[1, 0, 0],
       [2, 1, 0],
       [3, 4, 1]])

In [50]:
np.dot(L,A) # проверка

array([[ 1,  2,  4],
       [ 2,  9, 12],
       [ 3, 26, 30]])

2)б)

In [51]:
A = np.array([[1,1,2,4],[2,5,8,9],[3,18,29,18],[4,22,53,33]])
A

array([[ 1,  1,  2,  4],
       [ 2,  5,  8,  9],
       [ 3, 18, 29, 18],
       [ 4, 22, 53, 33]])

In [52]:
A[1] = A[1]-A[0]*2
A[2] = A[2]-A[0]*3
A[3] = A[3]-A[0]*4
A

array([[ 1,  1,  2,  4],
       [ 0,  3,  4,  1],
       [ 0, 15, 23,  6],
       [ 0, 18, 45, 17]])

In [53]:
A[2]=A[2]-A[1]*5
A[3]=A[3]-A[1]*6
A

array([[ 1,  1,  2,  4],
       [ 0,  3,  4,  1],
       [ 0,  0,  3,  1],
       [ 0,  0, 21, 11]])

In [54]:
A[3]=A[3]-A[2]*7
A

array([[1, 1, 2, 4],
       [0, 3, 4, 1],
       [0, 0, 3, 1],
       [0, 0, 0, 4]])

In [55]:
L = np.array([[1,0,0,0],[2,1,0,0],[3,5,1,0],[4,6,7,1]]) #ответ
L

array([[1, 0, 0, 0],
       [2, 1, 0, 0],
       [3, 5, 1, 0],
       [4, 6, 7, 1]])

In [56]:
np.dot(L,A) #проверка

array([[ 1,  1,  2,  4],
       [ 2,  5,  8,  9],
       [ 3, 18, 29, 18],
       [ 4, 22, 53, 33]])

3)

In [61]:
A = np.array([[2,1,3],[11,7,5],[9,8,4]],dtype='f')
A

array([[ 2.,  1.,  3.],
       [11.,  7.,  5.],
       [ 9.,  8.,  4.]], dtype=float32)

In [62]:
A[1]=A[1]-A[0]*5.5
A[2]=A[2]-A[0]*4.5
A

array([[  2. ,   1. ,   3. ],
       [  0. ,   1.5, -11.5],
       [  0. ,   3.5,  -9.5]], dtype=float32)

In [63]:
A[2] = A[2] - A[1]*(7/3)
A

array([[  2.      ,   1.      ,   3.      ],
       [  0.      ,   1.5     , -11.5     ],
       [  0.      ,   0.      ,  17.333332]], dtype=float32)

In [65]:
L = np.array([[1,0,0],[5.5,1,0],[4.5,7/3,1]],dtype='f')
L

array([[1.       , 0.       , 0.       ],
       [5.5      , 1.       , 0.       ],
       [4.5      , 2.3333333, 1.       ]], dtype=float32)

In [67]:
y1 = 1

In [70]:
y2 = -6-(5.5*y1)
y2

-11.5

In [71]:
y3 = -5 - 4.5*y1 -7/3*y2
y3

17.333333333333336

In [73]:
x3 = 1
x2 = (-11.5+11.5*x3)/1.5
x2

0.0

In [75]:
x1 = (1-x2 -3*x3)/2
x1

-1.0

4)